services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    container_name: laravel-nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  node:
    image: node:18
    working_dir: /var/www
    volumes:
      - ./:/app
    ports:
      - "5173:5173"
    command: npm run dev


  db:
    image: mysql:8.0
    container_name: laravel-mysql
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
